# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/danilo-alencar/Documents/GitHub/Aging-V2/Aging_V2/Aging_V2.runs/synth_1/croc_xilinx.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param power.BramSDPPropagationFix 1
set_param chipscope.maxJobs 2
set_param general.usePosixSpawnForFork 1
set_param xicom.use_bs_reader 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcau15p-ffvb676-1-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/danilo-alencar/Documents/GitHub/Aging-V2/Aging_V2/Aging_V2.cache/wt [current_project]
set_property parent.project_path /home/danilo-alencar/Documents/GitHub/Aging-V2/Aging_V2/Aging_V2.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/danilo-alencar/Documents/GitHub/Aging-V2/Aging_V2/Aging_V2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs {
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/apb/include
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/common_cells/include
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/include
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/obi/include
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/register_interface/include
} [current_fileset]
set_property verilog_define {TARGET_FPGA TARGET_AUP15 TARGET_XILINX WITH_SYSTEM_MONITOR WITH_TELEMETRY_TX WITH_SENSOR WITH_SENSOR_LF WITH_SENSOR_AM COMMON_CELLS_ASSERTS_OFF} [current_fileset]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/common_cells/include/common_cells/assertions.svh
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/common_cells/include/common_cells/registers.svh
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/obi/include/obi/typedef.svh
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/register_interface/include/register_interface/typedef.svh
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/include/lowrisc_prim/prim_assert_sec_cm.svh
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/include/lowrisc_prim/prim_assert_dummy_macros.svh
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/include/lowrisc_prim/prim_assert.svh
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/include/cve2/cve2_pmp_reset_default.svh
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/obi/include/obi/assign.svh
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/apb/include/apb/typedef.svh
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/register_interface/include/register_interface/assign.svh
}
set_property file_type "Verilog Header" [get_files /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/common_cells/include/common_cells/assertions.svh]
set_property file_type "Verilog Header" [get_files /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/common_cells/include/common_cells/registers.svh]
set_property file_type "Verilog Header" [get_files /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/obi/include/obi/typedef.svh]
set_property file_type "Verilog Header" [get_files /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/register_interface/include/register_interface/typedef.svh]
set_property file_type "Verilog Header" [get_files /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/include/lowrisc_prim/prim_assert_sec_cm.svh]
set_property file_type "Verilog Header" [get_files /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/include/lowrisc_prim/prim_assert_dummy_macros.svh]
set_property file_type "Verilog Header" [get_files /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/include/lowrisc_prim/prim_assert.svh]
set_property file_type "Verilog Header" [get_files /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/include/cve2/cve2_pmp_reset_default.svh]
set_property file_type "Verilog Header" [get_files /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/obi/include/obi/assign.svh]
set_property file_type "Verilog Header" [get_files /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/apb/include/apb/typedef.svh]
set_property file_type "Verilog Header" [get_files /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/register_interface/include/register_interface/assign.svh]
read_mem /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/sw/bin/helloworld.mem
read_verilog -library xil_defaultlib -sv {
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/common_cells/cf_math_pkg.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/common_cells/addr_decode.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/common_cells/addr_decode_dync.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/aging_sensor/aging_sensor.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/apb/apb_pkg.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/apb_uart/apb_uart.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/common_cells/cdc_2phase_clearable.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/common_cells/cdc_4phase.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/common_cells/cdc_reset_ctrlr_pkg.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/common_cells/cdc_reset_ctrlr.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/obi/obi_pkg.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/croc_pkg.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/cve2_pkg.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/riscv-dbg/dm_pkg.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/core_wrap.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/soc_ctrl/soc_ctrl_reg_pkg.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/croc_domain.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/croc_soc.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/cve2_alu.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/cve2_compressed_decoder.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/cve2_controller.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/cve2_core.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/cve2_counter.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/cve2_cs_registers.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/cve2_csr.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/cve2_decoder.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/cve2_ex_block.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/cve2_fetch_fifo.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/cve2_id_stage.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/cve2_if_stage.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/cve2_load_store_unit.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/cve2_multdiv_fast.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/cve2_multdiv_slow.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/cve2_pmp.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/cve2_prefetch_buffer.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/cve2_register_file_ff.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/cve2/cve2_wb.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/riscv-dbg/debug_rom/debug_rom.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/riscv-dbg/debug_rom/debug_rom_one_scratch.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/common_cells/delta_counter.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/riscv-dbg/dm_csrs.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/riscv-dbg/dm_mem.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/riscv-dbg/dm_obi_top.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/riscv-dbg/dm_sba.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/riscv-dbg/dm_top.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/riscv-dbg/dmi_cdc.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/riscv-dbg/dmi_jtag.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/riscv-dbg/dmi_jtag_tap.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/common_cells/fifo_v3.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/gpio/gpio_reg_pkg.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/gpio/gpio.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/gpio/gpio_reg_top.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/common_cells/lzc.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/obi/obi_demux.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/obi/obi_err_sbr.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/obi/obi_intf.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/obi/obi_mux.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/obi/obi_sram_shim.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/obi/obi_xbar.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/register_interface/periph_to_reg.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/register_interface/lowrisc_opentitan/prim_subreg.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/register_interface/lowrisc_opentitan/prim_subreg_arb.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/register_interface/reg_intf.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/register_interface/reg_to_apb.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/apb_uart/reg_uart_wrap.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/common_cells/rr_arb_tree.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/common_cells/rstgen.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/common_cells/rstgen_bypass.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/apb_uart/slib_clock_div.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/apb_uart/slib_counter.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/apb_uart/slib_edge_detect.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/apb_uart/slib_fifo.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/apb_uart/slib_input_filter.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/apb_uart/slib_input_sync.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/apb_uart/slib_mv_filter.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/soc_ctrl/soc_ctrl_reg_top.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/common_cells/spill_register.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/common_cells/spill_register_flushable.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/common_cells/sync.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/user_domain/system_monitor_usp.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/tech_cells_generic/fpga/tc_clk_xilinx.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/tech_cells_generic/tc_sram_impl.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/tech_cells_generic/fpga/tc_sram_xilinx.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/apb_uart/telemetry_tx.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/timer_unit/timer_unit.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/timer_unit/timer_unit_counter.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/timer_unit/timer_unit_counter_presc.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/apb_uart/uart_baudgen.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/apb_uart/uart_interrupt.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/apb_uart/uart_receiver.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/apb_uart/uart_router.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/apb_uart/uart_transmitter.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/user_pkg.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/user_domain.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/rtl_sensors/user_domain/user_sensor_monitor.sv
  /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/xilinx/hw/croc_xilinx_aging_sensors.sv
}
read_ip -quiet /home/danilo-alencar/Documents/GitHub/Aging-V2/Aging_V2/Aging_V2.srcs/sources_1/ip/sysmon_wiz_0/sysmon_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/danilo-alencar/Documents/GitHub/Aging-V2/Aging_V2/Aging_V2.gen/sources_1/ip/sysmon_wiz_0/sysmon_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/danilo-alencar/Documents/GitHub/Aging-V2/Aging_V2/Aging_V2.gen/sources_1/ip/sysmon_wiz_0/sysmon_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/danilo-alencar/Documents/GitHub/Aging-V2/Aging_V2/Aging_V2.gen/sources_1/ip/sysmon_wiz_0/sysmon_wiz_0.xdc]

read_ip -quiet /home/danilo-alencar/Documents/GitHub/Aging-V2/Aging_V2/Aging_V2.srcs/sources_1/ip/vio_2/vio_2.xci
set_property used_in_implementation false [get_files -all /home/danilo-alencar/Documents/GitHub/Aging-V2/Aging_V2/Aging_V2.gen/sources_1/ip/vio_2/vio_2.xdc]
set_property used_in_implementation false [get_files -all /home/danilo-alencar/Documents/GitHub/Aging-V2/Aging_V2/Aging_V2.gen/sources_1/ip/vio_2/vio_2_ooc.xdc]

read_ip -quiet /home/danilo-alencar/Documents/GitHub/Aging-V2/Aging_V2/Aging_V2.srcs/sources_1/ip/clk_wiz/clk_wiz.xci
set_property used_in_implementation false [get_files -all /home/danilo-alencar/Documents/GitHub/Aging-V2/Aging_V2/Aging_V2.gen/sources_1/ip/clk_wiz/clk_wiz_board.xdc]
set_property used_in_implementation false [get_files -all /home/danilo-alencar/Documents/GitHub/Aging-V2/Aging_V2/Aging_V2.gen/sources_1/ip/clk_wiz/clk_wiz.xdc]
set_property used_in_implementation false [get_files -all /home/danilo-alencar/Documents/GitHub/Aging-V2/Aging_V2/Aging_V2.gen/sources_1/ip/clk_wiz/clk_wiz_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/Constraints/fpga_aging_constraints.xdc
set_property used_in_implementation false [get_files /home/danilo-alencar/Documents/GitHub/Aging-V2/CROC/Constraints/fpga_aging_constraints.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top croc_xilinx -part xcau15p-ffvb676-1-i
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef croc_xilinx.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file croc_xilinx_utilization_synth.rpt -pb croc_xilinx_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
